language: node_js
node_js:
  - "0.10.x"
rvm:
  - "1.9.3"
before_install:
  - gem install jsduck -v=4
before_script:
  - component install
script:
  - grunt --verbose
  - grunt test --verbose
after_success:
  - chmod a+x node_modules/uick-grunt/update-gh-pages.sh
  - ./node_modules/uick-grunt/update-gh-pages.sh
env:
  global:
    - REPO="vieron/ui-input-slider"
    - secure: PW24n50GKaXdQIAjUTV/igXTzaU1ectN7ju3jR3QE5VYU/So6pVbb7kTtSrsdHLCzSEHX4tpnWACcfIkGTdgqif4yblHgIJiCJhNa+2QL8Zv+MYtRDDmFx9xPpg8kR/Cn1hTWrIz7L0I87sXd4zA8AXySAVZhdAtpfJ1sx0fLyE=
